"""Periodic digest: companies that just filed, ranked by what's likely next.

For every company in the current universe that reported a raise in the
digest window, show the model's chance of a bigger round (18 months) and of
going public (36 months), with the reasons behind each score.
"""

from __future__ import annotations

import datetime as dt
from dataclasses import dataclass
from pathlib import Path

import duckdb

from investup import backtest


@dataclass
class Digest:
    since: dt.date
    end: dt.date
    model: str
    universe_filers: int
    step_up: list[tuple]
    ipo_watch: list[tuple]
    biggest: list[tuple]


ROW_SQL = """
WITH recent AS (
    SELECT
        cik,
        max(known_at)                                                AS last_filing,
        sum(new_money) FILTER (WHERE NOT is_suspect_amount)          AS new_money,
        count(*) FILTER (WHERE is_new_offering)                      AS new_offerings
    FROM raise_event
    WHERE known_at > ? AND known_at <= ?
    GROUP BY cik
)
SELECT
    s.cik,
    s.entity_name,
    f.state,
    s.sector,
    r.last_filing,
    r.new_money,
    s.prob                                                           AS p_step_up,
    w.prob                                                           AS p_ipo,
    s.reason                                                         AS step_up_reason,
    w.reason                                                         AS ipo_reason
FROM recent AS r
JOIN digest_step_up AS s USING (cik)
LEFT JOIN digest_went_public AS w USING (cik)
LEFT JOIN score_rows AS f ON f.cik = s.cik AND f.as_of = s.as_of
"""


def build(
    con: duckdb.DuckDBPyConnection,
    *,
    since: dt.date | None = None,
    top: int = 25,
    model: str | None = None,
) -> Digest:
    model, _ = backtest.score_current(
        con, label="step_up", horizon=18, model=model, table="digest_step_up"
    )
    backtest.score_current(
        con, label="went_public", horizon=36, model=model, table="digest_went_public"
    )
    end = backtest.data_end(con)
    since = since or end - dt.timedelta(days=91)

    con.execute(f"CREATE OR REPLACE TEMP TABLE digest_rows AS {ROW_SQL}", [since, end])

    def fetch(order: str) -> list[tuple]:
        return con.execute(
            f"SELECT * FROM digest_rows ORDER BY {order}, hash(cik) LIMIT ?", [top]
        ).fetchall()

    return Digest(
        since=since,
        end=end,
        model=model,
        universe_filers=con.execute("SELECT count(*) FROM digest_rows").fetchone()[0],
        step_up=fetch("p_step_up DESC"),
        ipo_watch=fetch("p_ipo DESC NULLS LAST"),
        biggest=fetch("new_money DESC NULLS LAST"),
    )


def _money(x: float | None) -> str:
    if not x:
        return "–"
    return f"${x / 1e9:,.1f}B" if x >= 1e9 else f"${x / 1e6:,.1f}M"


def _table(rows: list[tuple], reason_col: int) -> list[str]:
    out = [
        "| Company | State | Sector | Filed | New money | P(bigger round, 18m) | "
        "P(IPO, 36m) | Why |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for r in rows:
        cik, name, state, sector, filed, money, p_step, p_ipo = r[:8]
        reason = (r[reason_col] or "").replace("|", "/")
        link = f"https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK={cik}&type=D"
        p_ipo_text = "–" if p_ipo is None else f"{p_ipo:.1%}"
        out.append(
            f"| [{name}]({link}) | {state or '–'} | {sector} | {filed} | {_money(money)} | "
            f"{p_step:.1%} | {p_ipo_text} | {reason} |"
        )
    return out


def render_markdown(d: Digest) -> str:
    lines = [
        f"# Investup digest: {d.since} to {d.end}",
        "",
        "Generated by `investup digest`. Don't edit by hand.",
        "",
        f"{d.universe_filers:,} private US venture-sector companies reported a raise to the SEC "
        f"(Form D) in this window. Scores come from the `{d.model}` model, trained only on "
        "outcomes that were already known. See `docs/backtests/` for how accurate each score "
        "has been historically.",
        "",
        "- **P(bigger round, 18m)**: chance of a new round of at least $5M and at least 1.5x "
        "the company's largest round so far, within 18 months.",
        "- **P(IPO, 36m)**: chance of a priced IPO or first periodic SEC report within 36 months.",
        "",
        "## Most likely to raise a bigger round",
        "",
        *_table(d.step_up, 8),
        "",
        "## IPO watch",
        "",
        *_table(d.ipo_watch, 9),
        "",
        "## Biggest raises reported in this window",
        "",
        *_table(d.biggest, 8),
        "",
        "## Caveats",
        "",
        "- Form D only covers companies that file. Some well-known companies raise through "
        "structures that don't file under their own name.",
        "- Acquisitions aren't tracked yet, so a company that was bought can still appear.",
        "- These are statistical scores from public filings, not investment advice.",
    ]
    return "\n".join(lines) + "\n"


def write(d: Digest, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_markdown(d))
